[package]
name = "advent2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day01"
path = "src/day01/main.rs"

[[bin]]
name = "day02"
path = "src/day02/main.rs"

[[bin]]
name = "day05"
path = "src/day05/main.rs"

[[bin]]
name = "default"
path = "src/main.rs"

